import { Montserrat } from "next/font/google";
import { Navbar } from "./components";

const inter = Montserrat({ subsets: ["latin"], variable: "--font-inter" });

export const metadata = {
  title: "Next.js",
  description: "Generated by Next.js",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body>
        <main
          className={`${inter.className} font-sans text-black bg-light w-full min-h-screen`}
        >
          <Navbar />
          {children}
        </main>
      </body>
    </html>
  );
}
