import { Montserrat } from "next/font/google";
import { Footer, Navbar } from "../components";

const mont = Montserrat({ subsets: ["latin"], variable: "--font-mont" });

export const metadata = {
  title: "Paulo Gomes - Porftolio",
  description: "Generated by Next.js",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body>
        <main
          className={`${mont.className} font-mont text-black bg-light w-full min-h-screen`}
        >
          <Navbar />
          {children}
          <Footer />
        </main>
      </body>
    </html>
  );
}
